branches:
  only:
    - master

sudo: required

services:
  - docker

before_install:
  - docker build -t lkblk/ftf-test -f ./client/Dockerfile.dev ./client

script:
  - docker run lkblk/ftf-test npm test -- --coverage

after_success:
  # Build production images
  - docker build -t lkblk/ftf-client ./client
  - docker build -t lkblk/ftf-server ./server
  
  # Log into DockerHub
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to DockerHub
  - docker push lkblk/ftf-client
  - docker push lkblk/ftf-server
