version: '3'

services:

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/api
      - /etc/fivetwentyfive.conf:/etc/fivetwentyfive.conf
    ports:
      - '5000:5000'

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
    depends_on:
      - api
