version: '3'

services:

  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    restart: always
    ports:
      - '3050:80'

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    env_file:
      - ./client/.env.local
    depends_on:
      - mongo

  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - '27017:27017'