version: '3'

services:

  mongo:
    image: mongo:bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: fivetwentyfive
    ports:
      - 27017:27017
    volumes:
      - ftfdb:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - ./api:/api
    ports:
      - 5000:8000
    depends_on:
      - mongo

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
      - 10000:10000
    depends_on:
      - api

volumes:
  ftfdb: