FROM python:3.7-alpine

WORKDIR /api

COPY ./requirements.txt .

RUN apk add --no-cache --update python3-dev  gcc build-base

RUN pip install -r requirements.txt

COPY . .

WORKDIR /

ENV FLASK_APP api

ENV FLASK_ENV development

CMD [ "flask", "run", "--host=0.0.0.0"]